'use strict';
const room=document.querySelector('#room'),actors=document.querySelector('#characters'),effects=document.querySelector('#effects');
const names=['ほおばまきちゃん','きのこ王子','にんじん兄さん','じゃがおじ'];
const calls=[['いっしょに！','えへへ','みーつけた！'],['ごきげんよう','森の香りだね','いいお天気だね'],['こっちだよ！','まかせて！','元気いっぱい！'],['ほっほっ','ひとやすみじゃ','いい日じゃのう']];
const people=names.map((name,i)=>({name,i,x:[.41,.57,.72,.56][i],y:[.65,.7,.65,.84][i],tx:0,ty:0,state:'idle',until:2+i*1.8,bubbleUntil:0,target:null,nextState:null,activityState:null}));
let elapsed=0,last=0,paused=false,mode='auto',modeUntil=0,ready=false,lastChat=0,treat=null,mushrooms=[],picked=0;
const rand=(a,b)=>a+Math.random()*(b-a);
const labels={idle:'のんびり',walk:'おさんぽ中',dance:'ごきげん♪',eat:'もぐもぐ',sleep:'すやすや',rest:'ひとやすみ',happy:'うれしい！',forage:'きのこ採り中'};
const restPoints=[[.16,.47],[.25,.46],[.55,.41],[.67,.42]];
function say(p,text,duration=3){p.bubble.textContent=text;p.bubbleUntil=elapsed+duration;}
function status(text){document.querySelector('#scene-status').textContent=text;}
function moment(text){document.querySelector('#moment-text').textContent=text;}
function state(p,value,seconds){p.state=value;p.until=elapsed+seconds;p.el.className='character '+({walk:'walking',dance:'dancing',sleep:'sleeping',rest:'resting',eat:'eating',happy:'happy',forage:'gathering'}[value]||'');document.querySelector('#status-'+p.i).textContent=labels[value];}
function float(p,text){const el=document.createElement('span');el.className='effect';el.textContent=text;el.style.left=p.x*100+'%';el.style.top=(p.y*100-12)+'%';effects.append(el);setTimeout(()=>el.remove(),1700);}
function release(p){if(p.target){p.target.owner=null;p.target=null;}}
function pet(i){if(!ready)return;const p=people[i];if(paused)setPause(false);release(p);state(p,'happy',2.5);say(p,calls[i][Math.floor(rand(0,3))]);float(p,'♡');moment(p.name+'、なでなでされてうれしそう。');}
function walk(p,x,y,nextState=null){p.tx=x;p.ty=y;p.nextState=nextState;state(p,'walk',15);}
function randomDestination(){return [rand(.38,.75),rand(.64,.85)];}
function choose(p){const n=Math.random();if(n<.55){walk(p,...randomDestination());}else if(n<.68){state(p,'dance',rand(3,6));say(p,['♪','ふふっ','体操しよう！','たまには踊るかの'][p.i]);}else if(n<.82){walk(p,...restPoints[p.i],p.i<2?'sleep':'rest');say(p,p.i<2?'すぅ…':'ひと休み…',5);}else{state(p,'idle',rand(2,4));say(p,calls[p.i][Math.floor(rand(0,3))]);}}
function setPause(value){paused=value;room.classList.toggle('paused',value);document.querySelector('#paused-note').hidden=!value;document.querySelector('#pause').setAttribute('aria-pressed',String(value));document.querySelector('#pause').setAttribute('aria-label',value?'動きを再開':'動きを一時停止');document.querySelector('#pause-icon').textContent=value?'▷':'Ⅱ';document.querySelector('#pause-label').textContent=value?'つづける':'ひとやすみ';}
function assignMushroom(p){const choices=mushrooms.filter(m=>!m.picked&&m.owner===null).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));if(!choices.length){state(p,'idle',1);return;}p.target=choices[0];p.target.owner=p.i;walk(p,p.target.x,p.target.y);document.querySelector('#status-'+p.i).textContent='きのこを探し中';}
function harvest(p){const m=p.target;if(m&&!m.picked){m.picked=true;m.el.remove();picked++;float(p,'🍄 +1');say(p,['採れた！','良いきのこだね','見つけたよ！','大収穫じゃ'][p.i]);status('🍄 きのこ '+picked+' / '+mushrooms.length+' 個');moment(p.name+'がきのこを採りました。');}release(p);state(p,'happy',1.5);if(picked===mushrooms.length){status('🍄 '+picked+'個、採れました！');moment('みんなで集めたきのこ、かごいっぱい。');modeUntil=elapsed+4;}}
function action(value){if(!['eat','forage','sleep','auto'].includes(value))throw Error('Unknown activity');if(!ready)return {status:'loading'};setPause(false);mode=value;modeUntil=value==='forage'?Infinity:elapsed+(value==='sleep'?23:18);people.forEach(p=>{release(p);p.nextState=null;p.activityState=null;});mushrooms.forEach(m=>m.el.remove());mushrooms=[];picked=0;if(treat){treat.remove();treat=null;}document.querySelectorAll('[data-action]').forEach(el=>{const a=el.dataset.action===value;el.classList.toggle('active',a);el.setAttribute('aria-pressed',String(a));});if(value==='auto'){people.forEach(p=>state(p,'idle',rand(.2,1.8)));status('それぞれの、のんびり時間');moment('みんな、思い思いに過ごしています。');return {activity:value};}
if(value==='forage'){const spots=[[.39,.67],[.51,.65],[.68,.66],[.77,.72],[.42,.79],[.54,.76],[.65,.82],[.54,.87]];mushrooms=spots.map(([x,y])=>{const el=document.createElement('span');el.className='mushroom';el.textContent='🍄';el.style.left=x*100+'%';el.style.top=y*100+'%';el.style.zIndex=String(Math.round(y*100)-1);actors.append(el);return {x,y,el,picked:false,owner:null};});people.forEach(p=>{assignMushroom(p);say(p,['きのこ、あるかな？','森の恵みだね','探しにいこう！','わしも行くかの'][p.i]);});status('🍄 きのこ 0 / 8 個');moment('お部屋できのこ採り。誰が先に見つけるかな？');return {activity:value};}
const points=value==='sleep'?restPoints:[[.43,.74],[.53,.67],[.66,.74],[.54,.85]];people.forEach((p,i)=>{p.activityState=value==='sleep'?(i<2?'sleep':'rest'):value;walk(p,...points[i]);say(p,value==='eat'?['おやつ！','お茶もどうぞ','食べよう！','いただきますじゃ'][i]:(i<2?['ふぁ…','すぅ…'][i]:['椅子でひと休み','のんびり休むかの'][i-2]));});if(value==='eat'){treat=document.createElement('span');treat.className='treat';treat.style.left='54%';treat.style.top='77%';treat.textContent='🍪';effects.append(treat);}status(value==='eat'?'みんなで、おやつの時間':'おへやも、しずかな時間に');moment(value==='eat'?'おやつに気づいて、みんなが集まってきた。':'きょうも、いっしょにひとやすみ。');return {activity:value};}
for(const p of people){const button=document.createElement('button');button.className='character';button.dataset.person=p.i;button.setAttribute('aria-label',p.name+'をなでる');button.innerHTML='<span class="char-shadow"></span><img alt="'+p.name+'" draggable="false"><span class="bubble"></span>';button.addEventListener('click',()=>pet(p.i));actors.append(button);p.el=button;p.bubble=button.querySelector('.bubble');button.style.left=p.x*100+'%';button.style.top=p.y*100+'%';}
document.querySelectorAll('.resident').forEach(el=>el.addEventListener('click',()=>pet(Number(el.dataset.person))));
document.querySelectorAll('[data-action]').forEach(el=>{el.setAttribute('aria-pressed',String(el.dataset.action==='auto'));el.addEventListener('click',()=>action(el.dataset.action));});document.querySelector('#pause').addEventListener('click',()=>setPause(!paused));
function tick(now){const dt=Math.min((now-last)/1000,.06);last=now;if(ready&&!paused&&!document.hidden){elapsed+=dt;if(mode!=='auto'&&elapsed>modeUntil)action('auto');for(const p of people){if(p.bubbleUntil<elapsed)p.bubble.textContent='';if(p.state==='walk'){const dx=p.tx-p.x,dy=p.ty-p.y,d=Math.hypot(dx,dy),step=[.05,.043,.063,.035][p.i]*dt;if(d<step+.002){p.x=p.tx;p.y=p.ty;if(mode==='forage'){state(p,'forage',1.1);}else{const v=p.nextState||(mode==='auto'?'idle':(p.activityState||mode));p.nextState=null;const duration=mode==='auto'?(v==='sleep'||v==='rest'?rand(6,10):rand(1,3)):Math.max(1,modeUntil-elapsed);state(p,v,duration);if(v==='eat')say(p,'もぐもぐ',4);if(v==='sleep')say(p,'zzz',duration);if(v==='rest')say(p,'ふぅ…',Math.min(4,duration));}}else{p.x+=dx/d*step;p.y+=dy/d*step;}}else if(elapsed>p.until){if(mode==='auto')choose(p);else if(mode==='forage'){if(p.state==='forage')harvest(p);else assignMushroom(p);}else state(p,p.activityState||mode,Math.max(1,modeUntil-elapsed));}p.el.style.left=p.x*100+'%';p.el.style.top=p.y*100+'%';p.el.style.zIndex=String(Math.round(p.y*100));}if(mode==='auto'&&elapsed-lastChat>15){lastChat=elapsed;const a=people[Math.floor(rand(0,people.length))],b=people[(a.i+1)%people.length];if(a.state!=='sleep'&&b.state!=='sleep'){say(a,calls[a.i][Math.floor(rand(0,3))]);say(b,['えへへ','うんうん','いいね！','そうじゃのう'][b.i]);moment(a.name+'と'+b.name+'、なにやらおしゃべり。');}}}requestAnimationFrame(tick);}
requestAnimationFrame(tick);
function extractSprite(atlas,i){
 const w=Math.floor(atlas.naturalWidth/4),h=atlas.naturalHeight,c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(atlas,i*w,0,w,h,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h);let x0=w,y0=h,x1=0,y1=0;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const k=(y*w+x)*4,d=pixels.data;const chroma=Math.min(d[k],d[k+2])-d[k+1];if(chroma>48){d[k+3]=0;}else if(d[k+3]>0){x0=Math.min(x0,x);y0=Math.min(y0,y);x1=Math.max(x1,x);y1=Math.max(y1,y);}}
 ctx.putImageData(pixels,0,0);const out=document.createElement('canvas');out.width=x1-x0+1;out.height=y1-y0+1;out.getContext('2d').drawImage(c,x0,y0,out.width,out.height,0,0,out.width,out.height);return out.toDataURL('image/png');
}
async function load(){try{const atlas=new Image();atlas.src='assets/forest-friends.png';await atlas.decode();await Promise.all(people.map(async(p)=>{const image=new Image();image.src=extractSprite(atlas,p.i);await image.decode();p.el.querySelector('img').src=image.src;document.querySelector('#avatar-'+p.i).append(image);}));await document.querySelector('#room-image').decode();ready=true;room.classList.add('ready');document.querySelector('#loading').remove();say(people[0],'いっしょに！');say(people[3],'いい部屋じゃのう');}catch(e){const el=document.querySelector('#loading');el.textContent='お部屋を読み込めませんでした。再読み込みしてください。';el.style.whiteSpace='normal';el.classList.add('failed');}}
load();
const context=document.modelContext;if(context?.registerTool){const life=new AbortController();try{Promise.resolve(context.registerTool({name:'set_room_activity',title:'みんなの過ごし方を選ぶ',description:'森のなかまのおやつ、きのこ採り、お昼寝、自由行動を開始する。',inputSchema:{type:'object',properties:{activity:{type:'string',enum:['eat','forage','sleep','auto']}},required:['activity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||Object.keys(input).length!==1||typeof input.activity!=='string')throw Error('activity is required');return action(input.activity);}},{signal:life.signal})).catch(()=>{});}catch(e){}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
